name: AWS Network Firewall Rules Update Request
description: Network Firewall Rules Update
title: "Network Firewall Rules Update Title"
labels: ["Rules Update"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Firewall Rules Update form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: incoming
    attributes:
      label: Select VPC
      description: Which VPC you want to Update The Firewall Rules
      options:
        - Ingress
        - Egress
    validations:
      required: true
  - type: dropdown
    id: rulename
    attributes:
      label: Provide Rule Type
      description: Which Firewall Rule you want to change
      options:
        - Stateless
        - Statefull
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Provide Details About Firewall Rules Update List
      description: Also tell us about Ingress or Egress Rules
      placeholder: Tell us what you see!
      value: "description About Rules Update"
    validations:
      required: true
